seed: 2023
version: mdc_test
device: cuda:0
output_dir: /content/mpcount_runs
persistent_dir: null
log_para: 1000
patch_size: 512
mode: final
checkpoint: null

model:
  name: final
  params:
    pretrained: false
    mem_size: 1024
    mem_dim: 256
    cls_thrs: 0.5
    err_thrs: 0.5
    den_dropout: 0.5
    cls_dropout: 0.3
    has_err_loss: false
    deterministic: true

test_dataset:
  name: mdc_den_cls
  params:
    root: /content/mdc_data/MovingDroneCrowd++
    crop_size: 320
    downsample: 1
    is_grey: false
    unit_size: 16
    pre_resize: 1.0
    sigma: 4.0
    density_radius: 7.0
    clip_points: true

test_loader:
  batch_size: 1
  num_workers: 2
  shuffle: false
  pin_memory: true
  persistent_workers: true

